services:
  web:
    image: nginx:alpine
    container_name: multi-web
    ports:
      - "8099:80"
    volumes:
      - ./web:/usr/share/nginx/html

  api:
    build: ./api
    container_name: multi-api
    ports:
      - "5000:5000"
