name: Dockerfile Optimization CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dockerfile-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build optimized Docker image
        run: docker build -t optimized-static-site ./month-02-git-github-cicd/day-16-dockerfile-optimization
